delete from BN_JOB_LOCK;
alter table BN_JOB_LOCK add LOCKED_BY_ varchar(55);
alter table BN_JOB_LOCK add PROC_UUID_ varchar(255);
alter table BN_JOB_LOCK add unique (PROC_UUID_);
create index IDX_JL_ on BN_JOB_LOCK (LOCKED_BY_, PROC_UUID_);
-- Need to drop the unique constraint before deleting the column
create index IDX_JL_PID_ on BN_JOB_LOCK (PROC_UUID_);

alter table BN_JOB_LOCK drop column PRI_UUID_;

drop index IDX_JB_LK_;
create index IDX_JB_LK_ on BN_JOB (RETRIES_);
alter table BN_JOB drop column LOCK_;
alter table BN_JOB alter column ROOT_INST_UUID_ rename to PROC_UUID_;

alter table BN_OEI_ add INCOMING_ID_ bigint;
drop index IDX_LOCK_;
create index IDX_LOCK_ on BN_OEI_ (OVERDUE, LOCKED);

create table BN_MASTER (DBID_ bigint generated by default as identity, HEARTBEAT_ bigint, NODE varchar(50), primary key (DBID_));
create table BN_NODE (DBID_ bigint generated by default as identity, HEARTBEAT_ bigint, NODE varchar(50), STATUS varchar(20), OPTION_ varchar(50), primary key (DBID_));